import catBridal from "@/assets/cat-bridal.jpg";
import catCasual from "@/assets/casual-wear.png";
import catChiffon from "@/assets/cat-chiffon.jpg";
import catEmbroidered from "@/assets/cat-embroidered.jpg";
import catLawn from "@/assets/cat-lawn.jpg";
import catUnstitched from "@/assets/cat-unstitched.jpg";

export interface Product {
  slug: string;
  name: string;
  price: string;
  description: string;
  sizes: string[];
  colors: string[];
  image: string;
  gallery: string[];
}

const ladiesSuits: Product[] = [
  {
    slug: "golden-embroidered-suit",
    name: "Golden Embroidered Suit",
    price: "PKR 24,500",
    description: "Soft lawn kameez with gold thread embroidery and a matching dupatta.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Ivory", "Champagne"],
    image: catEmbroidered,
    gallery: [catEmbroidered, catEmbroidered, catEmbroidered, catEmbroidered],
  },
  {
    slug: "pastel-floral-ensemble",
    name: "Pastel Floral Ensemble",
    price: "PKR 21,800",
    description: "Delicate floral print with subtle embellishments for daytime elegance.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blush", "Mint"],
    image: catEmbroidered,
    gallery: [catEmbroidered, catEmbroidered, catEmbroidered, catEmbroidered],
  },
  {
    slug: "chiffon-evening-set",
    name: "Chiffon Evening Set",
    price: "PKR 28,900",
    description: "Lightweight chiffon suit with hand-sewn beadwork and soft lining.",
    sizes: ["S", "M", "L"],
    colors: ["Navy", "Dusty Rose"],
    image: catEmbroidered,
    gallery: [catEmbroidered, catEmbroidered, catEmbroidered, catEmbroidered],
  },
  {
    slug: "classic-lawn-3-piece",
    name: "Classic Lawn 3-Piece",
    price: "PKR 18,400",
    description: "Everyday lawn with tasteful embroidery and easy tailoring.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Pine", "Peach"],
    image: catEmbroidered,
    gallery: [catEmbroidered, catEmbroidered, catEmbroidered, catEmbroidered],
  },
  {
    slug: "embroidered-formal-suit",
    name: "Embroidered Formal Suit",
    price: "PKR 26,200",
    description: "Structured embroidery with crisp trousers and a matching dupatta.",
    sizes: ["M", "L", "XL"],
    colors: ["Emerald", "Beige"],
    image: catEmbroidered,
    gallery: [catEmbroidered, catEmbroidered, catEmbroidered, catEmbroidered],
  },
  {
    slug: "handcrafted-mughal-suit",
    name: "Handcrafted Mughal Suit",
    price: "PKR 30,000",
    description: "Rich embroidery with statement sleeves and a refined finish.",
    sizes: ["S", "M", "L"],
    colors: ["Maroon", "Gold"],
    image: catEmbroidered,
    gallery: [catEmbroidered, catEmbroidered, catEmbroidered, catEmbroidered],
  },
  {
    slug: "soft-pastel-embellished-set",
    name: "Soft Pastel Embellished Set",
    price: "PKR 22,600",
    description: "Lightweight fabric and shimmering threadwork for festive wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Lilac", "Cream"],
    image: catEmbroidered,
    gallery: [catEmbroidered, catEmbroidered, catEmbroidered, catEmbroidered],
  },
  {
    slug: "pearl-detail-suit",
    name: "Pearl Detail Suit",
    price: "PKR 27,300",
    description: "Elegant pearl accents with a graceful silhouette and fine finish.",
    sizes: ["M", "L", "XL"],
    colors: ["Ivory", "Soft Pink"],
    image: catEmbroidered,
    gallery: [catEmbroidered, catEmbroidered, catEmbroidered, catEmbroidered],
  },
  {
    slug: "designer-lawn-combo",
    name: "Designer Lawn Combo",
    price: "PKR 19,900",
    description: "Tailored lawn design with a matching muslin dupatta.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Ocean", "Coral"],
    image: catEmbroidered,
    gallery: [catEmbroidered, catEmbroidered, catEmbroidered, catEmbroidered],
  },
  {
    slug: "signature-embroidery-suit",
    name: "Signature Embroidery Suit",
    price: "PKR 31,500",
    description: "Premium hand-embroidered suit for special evenings and celebrations.",
    sizes: ["M", "L", "XL"],
    colors: ["Olive", "Taupe"],
    image: catEmbroidered,
    gallery: [catEmbroidered, catEmbroidered, catEmbroidered, catEmbroidered],
  },
];

const casualWear: Product[] = [
  {
    slug: "linen-relaxed-set",
    name: "Linen Relaxed Set",
    price: "PKR 14,900",
    description: "Breathable linen tunic with a comfortable straight fit and soft tones.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige", "Sage"],
    image: catCasual,
    gallery: [catCasual, catCasual, catCasual, catCasual],
  },
  {
    slug: "cotton-comfort-suit",
    name: "Cotton Comfort Suit",
    price: "PKR 13,500",
    description: "Soft cotton kameez with easy trousers for everyday movement.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Sky Blue", "Ivory"],
    image: catCasual,
    gallery: [catCasual, catCasual, catCasual, catCasual],
  },
  {
    slug: "printed-summer-set",
    name: "Printed Summer Set",
    price: "PKR 15,200",
    description: "A breezy three-piece set in summer-ready prints and lightweight fabric.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Coral", "Mustard"],
    image: catCasual,
    gallery: [catCasual, catCasual, catCasual, catCasual],
  },
  {
    slug: "minimal-everyday-suit",
    name: "Minimal Everyday Suit",
    price: "PKR 12,800",
    description: "Structured simplicity with clean lines and minimal detailing.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Sand", "White"],
    image: catCasual,
    gallery: [catCasual, catCasual, catCasual, catCasual],
  },
  {
    slug: "soft-denim-tunic-set",
    name: "Soft Denim Tunic Set",
    price: "PKR 16,400",
    description: "Casual denim-inspired fabric with tailored comfort for daily wear.",
    sizes: ["S", "M", "L"],
    colors: ["Denim", "Grey"],
    image: catCasual,
    gallery: [catCasual, catCasual, catCasual, catCasual],
  },
  {
    slug: "relaxed-printed-kurta",
    name: "Relaxed Printed Kurta",
    price: "PKR 13,900",
    description: "Printed kurta with lounge-ready trousers and lightweight feel.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Olive", "Blush"],
    image: catCasual,
    gallery: [catCasual, catCasual, catCasual, catCasual],
  },
  {
    slug: "easygoing-shirt-suit",
    name: "Easygoing Shirt Suit",
    price: "PKR 14,200",
    description: "Soft shirt-style top paired with tapered trousers for a casual look.",
    sizes: ["S", "M", "L"],
    colors: ["Navy", "Stone"],
    image: catCasual,
    gallery: [catCasual, catCasual, catCasual, catCasual],
  },
  {
    slug: "weekend-lounge-outfit",
    name: "Weekend Lounge Outfit",
    price: "PKR 12,300",
    description: "Relaxed silhouette made for comfort and effortless style.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Mauve", "Olive"],
    image: catCasual,
    gallery: [catCasual, catCasual, catCasual, catCasual],
  },
  {
    slug: "lightweight-cotton-set",
    name: "Lightweight Cotton Set",
    price: "PKR 13,600",
    description: "Soft cotton blend for easy wear with subtle stitched detailing.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Mint", "Vanilla"],
    image: catCasual,
    gallery: [catCasual, catCasual, catCasual, catCasual],
  },
  {
    slug: "day-to-day-printed-suit",
    name: "Day-to-Day Printed Suit",
    price: "PKR 15,100",
    description: "Printed statement set designed for comfort and everyday confidence.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Teal", "Coral"],
    image: catCasual,
    gallery: [catCasual, catCasual, catCasual, catCasual],
  },
];

const partyWear: Product[] = [
  {
    slug: "sequin-gala-suit",
    name: "Sequin Gala Suit",
    price: "PKR 34,800",
    description: "Sparkling sequins on a flowing silhouette for unforgettable evenings.",
    sizes: ["S", "M", "L"],
    colors: ["Gold", "Black"],
    image: catBridal,
    gallery: [catBridal, catBridal, catBridal, catBridal],
  },
  {
    slug: "velvet-party-set",
    name: "Velvet Party Set",
    price: "PKR 36,500",
    description: "Soft velvet with rich embroidery and dramatic sleeves.",
    sizes: ["M", "L", "XL"],
    colors: ["Maroon", "Emerald"],
    image: catBridal,
    gallery: [catBridal, catBridal, catBridal, catBridal],
  },
  {
    slug: "crystal-embellished-suit",
    name: "Crystal Embellished Suit",
    price: "PKR 32,900",
    description: "Delicate crystal work paired with luxurious chiffon fabric.",
    sizes: ["S", "M", "L"],
    colors: ["Silver", "Blush"],
    image: catBridal,
    gallery: [catBridal, catBridal, catBridal, catBridal],
  },
  {
    slug: "evening-garden-outfit",
    name: "Evening Garden Outfit",
    price: "PKR 29,700",
    description: "Floral motifs and soft layers for romantic party wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Dusty Pink", "Lavender"],
    image: catBridal,
    gallery: [catBridal, catBridal, catBridal, catBridal],
  },
  {
    slug: "grand-celebration-suit",
    name: "Grand Celebration Suit",
    price: "PKR 38,200",
    description: "Regal embroidery with structured tailoring for landmark events.",
    sizes: ["M", "L", "XL"],
    colors: ["Navy", "Cream"],
    image: catBridal,
    gallery: [catBridal, catBridal, catBridal, catBridal],
  },
  {
    slug: "satin-evening-set",
    name: "Satin Evening Set",
    price: "PKR 31,600",
    description: "Silky sheen and refined detailing for an elevated evening look.",
    sizes: ["S", "M", "L"],
    colors: ["Champagne", "Rose"],
    image: catBridal,
    gallery: [catBridal, catBridal, catBridal, catBridal],
  },
  {
    slug: "party-chic-suit",
    name: "Party Chic Suit",
    price: "PKR 28,950",
    description: "Modern cut with glittering accents for after-dark celebrations.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Silver"],
    image: catBridal,
    gallery: [catBridal, catBridal, catBridal, catBridal],
  },
  {
    slug: "evening-luxe-ensemble",
    name: "Evening Luxe Ensemble",
    price: "PKR 35,400",
    description: "Rich textures and contrasting embroidery for striking appeal.",
    sizes: ["M", "L", "XL"],
    colors: ["Burgundy", "Gold"],
    image: catBridal,
    gallery: [catBridal, catBridal, catBridal, catBridal],
  },
  {
    slug: "sparkling-formal-suit",
    name: "Sparkling Formal Suit",
    price: "PKR 33,700",
    description: "Glitter details and elegant draping perfect for celebrations.",
    sizes: ["S", "M", "L"],
    colors: ["Teal", "Platinum"],
    image: catBridal,
    gallery: [catBridal, catBridal, catBridal, catBridal],
  },
  {
    slug: "statement-party-set",
    name: "Statement Party Set",
    price: "PKR 37,600",
    description: "Bold cutwork and shimmering accents for a memorable look.",
    sizes: ["M", "L", "XL"],
    colors: ["Royal Blue", "Ivory"],
    image: catBridal,
    gallery: [catBridal, catBridal, catBridal, catBridal],
  },
];

const kidsCollection: Product[] = [
  {
    slug: "mini-floral-suit",
    name: "Mini Floral Suit",
    price: "PKR 11,200",
    description: "Soft cotton with playful floral prints for little celebrations.",
    sizes: ["2-3", "4-5", "6-7"],
    colors: ["Pink", "Yellow"],
    image: catLawn,
    gallery: [catLawn, catLawn, catLawn, catLawn],
  },
  {
    slug: "tiny-comfort-set",
    name: "Tiny Comfort Set",
    price: "PKR 10,500",
    description: "Lightweight fabric with easy movement for all-day play.",
    sizes: ["2-3", "4-5", "6-7", "8-9"],
    colors: ["Blue", "Grey"],
    image: catLawn,
    gallery: [catLawn, catLawn, catLawn, catLawn],
  },
  {
    slug: "playful-print-suit",
    name: "Playful Print Suit",
    price: "PKR 11,900",
    description: "Bright prints and soft stitching for joyful weekend looks.",
    sizes: ["2-3", "4-5", "6-7"],
    colors: ["Green", "Orange"],
    image: catLawn,
    gallery: [catLawn, catLawn, catLawn, catLawn],
  },
  {
    slug: "party-ready-kids-set",
    name: "Party-ready Kids Set",
    price: "PKR 12,600",
    description: "Dressy details with comfortable fit for little guests.",
    sizes: ["4-5", "6-7", "8-9"],
    colors: ["Purple", "Silver"],
    image: catLawn,
    gallery: [catLawn, catLawn, catLawn, catLawn],
  },
  {
    slug: "school-day-suit",
    name: "School Day Suit",
    price: "PKR 10,100",
    description: "Crisp style with durable fabric for everyday school wear.",
    sizes: ["2-3", "4-5", "6-7", "8-9"],
    colors: ["Navy", "White"],
    image: catLawn,
    gallery: [catLawn, catLawn, catLawn, catLawn],
  },
  {
    slug: "weekend-fun-outfit",
    name: "Weekend Fun Outfit",
    price: "PKR 11,800",
    description: "Casual print with breathable fabric for family outings.",
    sizes: ["2-3", "4-5", "6-7"],
    colors: ["Turquoise", "Coral"],
    image: catLawn,
    gallery: [catLawn, catLawn, catLawn, catLawn],
  },
  {
    slug: "petite-embellished-suit",
    name: "Petite Embellished Suit",
    price: "PKR 12,900",
    description: "Subtle embellishments and flattering cuts for special days.",
    sizes: ["4-5", "6-7", "8-9"],
    colors: ["Cream", "Rose"],
    image: catLawn,
    gallery: [catLawn, catLawn, catLawn, catLawn],
  },
  {
    slug: "comfort-knit-set",
    name: "Comfort Knit Set",
    price: "PKR 10,700",
    description: "Stretchy knit with relaxed ease for active little ones.",
    sizes: ["2-3", "4-5", "6-7"],
    colors: ["Mint", "Beige"],
    image: catLawn,
    gallery: [catLawn, catLawn, catLawn, catLawn],
  },
  {
    slug: "bright-day-suit",
    name: "Bright Day Suit",
    price: "PKR 11,300",
    description: "Vibrant colors and soft fabric for happy everyday wear.",
    sizes: ["4-5", "6-7", "8-9"],
    colors: ["Sunset", "Sky"],
    image: catLawn,
    gallery: [catLawn, catLawn, catLawn, catLawn],
  },
  {
    slug: "festive-kids-ensemble",
    name: "Festive Kids Ensemble",
    price: "PKR 13,200",
    description: "Light embroidery with a comfortable fit for family celebrations.",
    sizes: ["4-5", "6-7", "8-9"],
    colors: ["Gold", "Teal"],
    image: catLawn,
    gallery: [catLawn, catLawn, catLawn, catLawn],
  },
];

const winterCollection: Product[] = [
  {
    slug: "velvet-winter-suit",
    name: "Velvet Winter Suit",
    price: "PKR 33,500",
    description: "Warm velvet with luxurious embroidery and soft lining.",
    sizes: ["M", "L", "XL"],
    colors: ["Burgundy", "Black"],
    image: catUnstitched,
    gallery: [catUnstitched, catUnstitched, catUnstitched, catUnstitched],
  },
  {
    slug: "woolen-layered-set",
    name: "Woolen Layered Set",
    price: "PKR 31,200",
    description: "Layered wool blend set with cozy silhouettes and elegant detailing.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Charcoal", "Cream"],
    image: catUnstitched,
    gallery: [catUnstitched, catUnstitched, catUnstitched, catUnstitched],
  },
  {
    slug: "cashmere-inspired-suit",
    name: "Cashmere-inspired Suit",
    price: "PKR 35,900",
    description: "Luxurious textured fabric with a flattering fall and warmth.",
    sizes: ["M", "L", "XL"],
    colors: ["Oatmeal", "Olive"],
    image: catUnstitched,
    gallery: [catUnstitched, catUnstitched, catUnstitched, catUnstitched],
  },
  {
    slug: "embroidered-shawl-set",
    name: "Embroidered Shawl Set",
    price: "PKR 29,700",
    description: "Soft shawl detailing paired with a winter-ready suit.",
    sizes: ["S", "M", "L"],
    colors: ["Navy", "Stone"],
    image: catUnstitched,
    gallery: [catUnstitched, catUnstitched, catUnstitched, catUnstitched],
  },
  {
    slug: "cozy-knit-suit",
    name: "Cozy Knit Suit",
    price: "PKR 28,400",
    description: "Knitted textures with a relaxed fit for everyday warmth.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Brown", "Mustard"],
    image: catUnstitched,
    gallery: [catUnstitched, catUnstitched, catUnstitched, catUnstitched],
  },
  {
    slug: "fleece-lined-formal",
    name: "Fleece-lined Formal",
    price: "PKR 34,100",
    description: "Structured formal suit with fleece lining for cold evenings.",
    sizes: ["M", "L", "XL"],
    colors: ["Midnight", "Platinum"],
    image: catUnstitched,
    gallery: [catUnstitched, catUnstitched, catUnstitched, catUnstitched],
  },
  {
    slug: "winter-pastel-suit",
    name: "Winter Pastel Suit",
    price: "PKR 30,800",
    description: "Soft pastel tones with insulated fabric for cooler days.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Lilac", "Silver"],
    image: catUnstitched,
    gallery: [catUnstitched, catUnstitched, catUnstitched, catUnstitched],
  },
  {
    slug: "layered-festive-set",
    name: "Layered Festive Set",
    price: "PKR 36,700",
    description: "A layered look with detailed embroidery fit for winter festivities.",
    sizes: ["M", "L", "XL"],
    colors: ["Forest", "Gold"],
    image: catUnstitched,
    gallery: [catUnstitched, catUnstitched, catUnstitched, catUnstitched],
  },
  {
    slug: "classic-winter-ensemble",
    name: "Classic Winter Ensemble",
    price: "PKR 32,300",
    description: "Timeless cut with warming fabrics and polished finishes.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy", "Taupe"],
    image: catUnstitched,
    gallery: [catUnstitched, catUnstitched, catUnstitched, catUnstitched],
  },
  {
    slug: "highland-elegance-suit",
    name: "Highland Elegance Suit",
    price: "PKR 38,000",
    description: "Sophisticated winter design with rich textures and warmth.",
    sizes: ["M", "L", "XL"],
    colors: ["Wine", "Ivory"],
    image: catUnstitched,
    gallery: [catUnstitched, catUnstitched, catUnstitched, catUnstitched],
  },
];

const newArrivals: Product[] = [
  {
    slug: "modern-lace-suit",
    name: "Modern Lace Suit",
    price: "PKR 29,500",
    description: "Delicate lace and contemporary tailoring for the latest arrivals.",
    sizes: ["S", "M", "L"],
    colors: ["Cream", "Blush"],
    image: catChiffon,
    gallery: [catChiffon, catChiffon, catChiffon, catChiffon],
  },
  {
    slug: "textured-silk-set",
    name: "Textured Silk Set",
    price: "PKR 31,800",
    description: "Silky textures and subtle shine for a fresh wardrobe choice.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Champagne", "Pearl"],
    image: catChiffon,
    gallery: [catChiffon, catChiffon, catChiffon, catChiffon],
  },
  {
    slug: "statement-printed-suit",
    name: "Statement Printed Suit",
    price: "PKR 26,200",
    description: "Bold prints with contemporary styling for modern wearers.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Rust", "Navy"],
    image: catChiffon,
    gallery: [catChiffon, catChiffon, catChiffon, catChiffon],
  },
  {
    slug: "designer-wrap-set",
    name: "Designer Wrap Set",
    price: "PKR 28,900",
    description: "Novel wrap details and fine finishing make this a season standout.",
    sizes: ["S", "M", "L"],
    colors: ["Sage", "Terracotta"],
    image: catChiffon,
    gallery: [catChiffon, catChiffon, catChiffon, catChiffon],
  },
  {
    slug: "classic-new-drop-suit",
    name: "Classic New Drop Suit",
    price: "PKR 24,100",
    description: "Fresh silhouettes in breathable fabrics for updated everyday wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Olive", "Beige"],
    image: catChiffon,
    gallery: [catChiffon, catChiffon, catChiffon, catChiffon],
  },
  {
    slug: "elegant-chiffon-ensemble",
    name: "Elegant Chiffon Ensemble",
    price: "PKR 32,000",
    description: "Soft chiffon with elegant detailing for new season gatherings.",
    sizes: ["S", "M", "L"],
    colors: ["Peach", "Ivory"],
    image: catChiffon,
    gallery: [catChiffon, catChiffon, catChiffon, catChiffon],
  },
  {
    slug: "summer-silk-suit",
    name: "Summer Silk Suit",
    price: "PKR 27,300",
    description: "Light silk feel with crisp finish for warmer days.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "White"],
    image: catChiffon,
    gallery: [catChiffon, catChiffon, catChiffon, catChiffon],
  },
  {
    slug: "draped-trend-set",
    name: "Draped Trend Set",
    price: "PKR 30,400",
    description: "Contemporary drape and structured details for the latest wardrobe additions.",
    sizes: ["S", "M", "L"],
    colors: ["Grey", "Mauve"],
    image: catChiffon,
    gallery: [catChiffon, catChiffon, catChiffon, catChiffon],
  },
  {
    slug: "minimalist-new-arrival",
    name: "Minimalist New Arrival",
    price: "PKR 25,700",
    description: "Clean lines and subtle flair for a refined seasonal statement.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Sand", "Ivory"],
    image: catChiffon,
    gallery: [catChiffon, catChiffon, catChiffon, catChiffon],
  },
  {
    slug: "fresh-embellished-set",
    name: "Fresh Embellished Set",
    price: "PKR 33,100",
    description: "New arrival with delicate embellishments and modern appeal.",
    sizes: ["S", "M", "L"],
    colors: ["Blush", "Gold"],
    image: catChiffon,
    gallery: [catChiffon, catChiffon, catChiffon, catChiffon],
  },
];

export const categoryProducts = {
  ladiesSuits,
  casualWear,
  partyWear,
  kidsCollection,
  winterCollection,
  newArrivals,
};

export const allProducts = [
  ...ladiesSuits,
  ...casualWear,
  ...partyWear,
  ...kidsCollection,
  ...winterCollection,
  ...newArrivals,
];

const productMap = new Map(allProducts.map((product) => [product.slug, product]));

export function getProductBySlug(slug: string | undefined) {
  return slug ? productMap.get(slug) : undefined;
}
